# Generated by Django 5.1.1 on 2024-09-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weight",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
